include make.inc

ifndef MPI
MPI=1
endif

ifeq ($(MPI),1)
CC=$(MPICC)
CXX=$(MPICXX)
else
CC=$(TCC)
CXX=$(TCXX)
endif

OS=$(shell uname)
VERSION=0.1

ARCH_FLAGS=-m64
CFLAGS=-Wextra -Wall -pedantic-errors -O3 -fPIC -fno-common $(ARCH_FLAGS)
LDFLAGS=$(ARCH_FLAGS) 
DEFINES=-D __BLAS_LEGACY__
INCLUDES=-Iinclude/ -I$(MOSEK)/h $(CBLAS_INC)
MOSEKLIB=-L$(MOSEK)/bin -Wl,-rpath,$(MOSEK)/bin -lmosek64 -lpthread
LIBRARIES=$(BLAS_LIB) $(OTHER_LIB)

CPP_SOURCE_FILES=\
	src/d2/solver_mosek.cc\

SOURCE_FILES_WITH_MAIN=\
	src/app/util.cc\
	src/app/main.cc

ALL_OBJECTS=\
	$(CPP_SOURCE_OBJECTS)\
	$(patsubst %.cc, %.o, $(SOURCE_FILES_WITH_MAIN))

DEPENDENCY_FILES=\
	$(patsubst %.o, %.d, $(ALL_OBJECTS))

ifeq ($(OS), Darwin)
LIB=\
	libad2c.dylib\
	libmosek64_wrapper.dylib
else
LIB=\
	libad2c.so\
	libmosek64_wrapper.so
endif


all: d2 protein

lib: $(LIB) 

%.o: %.cc Makefile
	@# Make dependecy file
	$(CXX) -MM -MT $@ -MF $(patsubst %.cc,%.d,$<) $(CFLAGS) $(DEFINES) $(INCLUDES) $<
	@# Compile
	$(CXX) $(CFLAGS) $(DEFINES) $(INCLUDES) -c -o $@ $<

d2: src/app/util.cc src/app/main.cc $(LIB)
	$(CXX) $(LDFLAGS) $(DEFINES) $(INCLUDES) -o $@ $^ $(LIBRARIES) $(MOSEKLIB)

data/protein_seq/protein: data/protein_seq/d2_protein_ngram.cc $(LIB)
	$(CXX) $(LDFLAGS) $(DEFINES) $(INCLUDES) -o $@ $^ $(LIBRARIES) $(MOSEKLIB)


ifeq ($(OS), Darwin)
libmosek64_wrapper.dylib: src/d2/solver_mosek.o
	$(TCXX) -dynamiclib $(DEFINES) $(INCLUDES) -Wl,-install_name,$@ -compatibility_version 7.0 -current_version $(MOSEK_VERSION) -o libmosek64_wrapper.$(MOSEK_VERSION).dylib $< $(MOSEKLIB) $(LIBRARIES) 
	install_name_tool -change  @loader_path/libmosek64.$(MOSEK_VERSION).dylib  $(MOSEK)/bin/libmosek64.$(MOSEK_VERSION).dylib libmosek64_wrapper.$(MOSEK_VERSION).dylib
	ln -sf libmosek64_wrapper.$(MOSEK_VERSION).dylib $@ 
else
libmosek64_wrapper.so: src/d2/solver_mosek.o
	$(TCXX) -shared $(DEFINES) $(INCLUDES) -Wl,-soname,$@ -o libmosek64_wrapper.$(MOSEK_VERSION).so $< $(MOSEKLIB) $(LIBRARIES) 
	ln -sf libmosek64_wrapper.$(MOSEK_VERSION).so $@ 
endif


-include $(DEPENDENCY_FILES)


protein: data/protein_seq/protein

.PHONY: clean test
clean:
	@rm -f libmosek64_wrapper*.so
	@rm -f d2 data/protein_seq/protein
	@for pattern in '*.o' '*.d'; do \
		find . -name "$$pattern" | xargs rm; \
	done

ifeq ($(MPI),1)
test:
	cd test && ./test_mpi.sh
else
test:
	cd test && ./test_single.sh
endif


